apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-toto-MonApppp-frontend-cert
  namespace: dev-toto-MonApppp-frontend
spec:
  secretName: dev-toto-MonApppp-frontend-tls
  dnsNames:
    - dev.testdomain.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
