apiVersion: v1
kind: Service
metadata:
  name: dev-toto-MonApppp-frontend-service
  namespace: dev-toto-MonApppp-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: dev-toto-MonApppp-frontend
