apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-toto-MonApppp-frontend-cert
  namespace: staging-toto-MonApppp-frontend
spec:
  secretName: staging-toto-MonApppp-frontend-tls
  dnsNames:
    - staging.testdomain.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
