apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-toto-MonApppp-frontend-ingress
  namespace: prod-toto-MonApppp-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - testdomain.flapi.org
      secretName: prod-toto-MonApppp-frontend-tls
  rules:
    - host: testdomain.flapi.org
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: prod-toto-MonApppp-frontend-service
                port:
                  number: 3000
