apiVersion: v1
kind: Service
metadata:
  name: prod-toto-MonApppp-frontend-service
  namespace: prod-toto-MonApppp-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: prod-toto-MonApppp-frontend
